INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AD', N'Andorra');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AE', N'Emiratos Árabes Unidos');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AF', N'Afganistán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AG', N'Antigua y Barbuda');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AI', N'Anguila');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AL', N'Albania');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AM', N'Armenia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AO', N'Angola');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AQ', N'Antártida');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AR', N'Argentina');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AS', N'Samoa Americana');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AT', N'Austria');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AU', N'Australia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AW', N'Aruba');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AX', N'Islas Åland');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'AZ', N'Azerbaiyán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BA', N'Bosnia y Herzegovina');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BB', N'Barbados');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BD', N'Bangladés');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BE', N'Bélgica');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BF', N'Burkina Faso');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BG', N'Bulgaria');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BH', N'Bahréin');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BI', N'Burundi');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BJ', N'Benín');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BL', N'Saint Barthélemy');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BM', N'Bermudas');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BN', N'Brunéi');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BO', N'Bolivia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BQ', N'Caribe Neerlandés');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BR', N'Brasil');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BS', N'Bahamas');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BT', N'Bután');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BV', N'Isla Bouvet');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BW', N'Botsuana');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BY', N'Bielorrusia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'BZ', N'Belice');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CA', N'Canadá');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CC', N'Islas Cocos');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CD', N'República Democrática del Congo');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CF', N'República Centroafricana');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CG', N'Congo');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CH', N'Suiza');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CI', N'Costa de Marfil');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CK', N'Islas Cook');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CL', N'Chile');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CM', N'Camerún');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CN', N'China');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CO', N'Colombia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CR', N'Costa Rica');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CU', N'Cuba');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CV', N'Cabo Verde');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CW', N'Curaçao');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CX', N'Isla de Navidad');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CY', N'Chipre');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'CZ', N'Chequia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'DE', N'Alemania');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'DJ', N'Yibuti');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'DK', N'Dinamarca');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'DM', N'Dominica');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'DO', N'República Dominicana');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'DZ', N'Argelia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'EC', N'Ecuador');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'EE', N'Estonia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'EG', N'Egipto');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'EH', N'Sahara Occidental');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'ER', N'Eritrea');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'ES', N'España');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'ET', N'Etiopía');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'FI', N'Finlandia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'FJ', N'Fiyi');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'FK', N'Islas Malvinas');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'FM', N'Micronesia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'FO', N'Islas Feroe');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'FR', N'Francia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GA', N'Gabón');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GB', N'Reino Unido');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GD', N'Granada');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GE', N'Georgia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GF', N'Guayana Francesa');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GG', N'Guernesey');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GH', N'Ghana');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GI', N'Gibraltar');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GL', N'Groenlandia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GM', N'Gambia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GN', N'Guinea');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GP', N'Guadalupe');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GQ', N'Guinea Ecuatorial');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GR', N'Grecia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GS', N'Georgia del Sur e Islas Sandwich del Sur');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GT', N'Guatemala');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GU', N'Guam');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GW', N'Guinea-Bisáu');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'GY', N'Guyana');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'HK', N'Hong Kong');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'HM', N'Islas Heard y McDonald');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'HN', N'Honduras');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'HR', N'Croacia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'HT', N'Haití');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'HU', N'Hungría');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'ID', N'Indonesia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'IE', N'Irlanda');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'IL', N'Israel');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'IM', N'Isla de Man');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'IN', N'India');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'IO', N'Territorio Británico del Océano Índico');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'IQ', N'Irak');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'IR', N'Irán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'IS', N'Islandia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'IT', N'Italia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'JE', N'Jersey');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'JM', N'Jamaica');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'JO', N'Jordania');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'JP', N'Japón');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'KE', N'Kenia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'KG', N'Kirguistán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'KH', N'Camboya');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'KI', N'Kiribati');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'KM', N'Comoras');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'KN', N'Saint Kitts y Nevis');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'KP', N'Corea del Norte');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'KR', N'Corea del Sur');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'KW', N'Kuwait');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'KY', N'Islas Caimán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'KZ', N'Kazajistán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'LA', N'Laos');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'LB', N'Líbano');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'LC', N'Santa Lucía');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'LI', N'Liechtenstein');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'LK', N'Sri Lanka');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'LR', N'Liberia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'LS', N'Lesoto');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'LT', N'Lituania');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'LU', N'Luxemburgo');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'LV', N'Letonia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'LY', N'Libia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MA', N'Marruecos');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MC', N'Mónaco');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MD', N'Moldavia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'ME', N'Montenegro');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MF', N'Saint Martin');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MG', N'Madagascar');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MH', N'Islas Marshall');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MK', N'Macedonia del Norte');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'ML', N'Malí');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MM', N'Myanmar');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MN', N'Mongolia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MO', N'Macao');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MP', N'Islas Marianas del Norte');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MQ', N'Martinica');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MR', N'Mauritania');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MS', N'Montserrat');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MT', N'Malta');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MU', N'Mauricio');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MV', N'Maldivas');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MW', N'Malaui');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MX', N'México');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MY', N'Malasia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'MZ', N'Mozambique');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'NA', N'Namibia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'NC', N'Nueva Caledonia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'NE', N'Níger');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'NF', N'Isla Norfolk');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'NG', N'Nigeria');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'NI', N'Nicaragua');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'NL', N'Países Bajos');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'NO', N'Noruega');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'NP', N'Nepal');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'NR', N'Nauru');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'NU', N'Niue');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'NZ', N'Nueva Zelanda');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'OM', N'Omán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PA', N'Panamá');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PE', N'Perú');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PF', N'Polinesia Francesa');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PG', N'Papúa Nueva Guinea');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PH', N'Filipinas');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PK', N'Pakistán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PL', N'Polonia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PM', N'Saint Pierre y Miquelon');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PN', N'Islas Pitcairn');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PR', N'Puerto Rico');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PS', N'Palestina');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PT', N'Portugal');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PW', N'Palaos');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'PY', N'Paraguay');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'QA', N'Catar');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'RE', N'Reunión');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'RO', N'Rumanía');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'RS', N'Serbia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'RU', N'Rusia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'RW', N'Ruanda');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SA', N'Arabia Saudita');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SB', N'Islas Salomón');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SC', N'Seychelles');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SD', N'Sudán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SE', N'Suecia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SG', N'Singapur');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SH', N'Santa Elena');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SI', N'Eslovenia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SJ', N'Svalbard y Jan Mayen');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SK', N'Eslovaquia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SL', N'Sierra Leona');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SM', N'San Marino');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SN', N'Senegal');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SO', N'Somalia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SR', N'Surinam');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SS', N'Sudán del Sur');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'ST', N'Santo Tomé y Príncipe');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SV', N'El Salvador');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SX', N'Sint Maarten');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'SY', N'Siria');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TC', N'Islas Turcas y Caicos');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TD', N'Chad');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TF', N'Tierras Australes Francesas');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TG', N'Togo');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TH', N'Tailandia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TJ', N'Tayikistán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TK', N'Tokelau');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TL', N'Timor Oriental');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TM', N'Turkmenistán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TN', N'Túnez');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TO', N'Tonga');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TR', N'Turquía');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TT', N'Trinidad y Tobago');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TV', N'Tuvalu');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TW', N'Taiwán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'TZ', N'Tanzania');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'UA', N'Ucrania');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'UG', N'Uganda');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'UM', N'Islas Ultramarinas de Estados Unidos');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'US', N'Estados Unidos');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'UY', N'Uruguay');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'UZ', N'Uzbekistán');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'VA', N'Ciudad del Vaticano');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'VC', N'Saint Vincent y las Granadinas');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'VE', N'Venezuela');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'VG', N'Islas Vírgenes Británicas');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'VI', N'Islas Vírgenes de los Estados Unidos');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'VN', N'Vietnam');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'VU', N'Vanuatu');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'WF', N'Wallis y Futuna');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'WS', N'Samoa');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'YE', N'Yemen');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'YT', N'Mayotte');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'ZA', N'Sudáfrica');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'ZM', N'Zambia');
INSERT INTO crud_semana_2.dbo.Paises (Codigo, Pais) VALUES (N'ZW', N'Zimbabue');
